### ISSUE TITLE
mangagreat.com

### ISSUE THREAD

**Issue by Alanray64** [Paperback-iOS/extensions-promises#198] opened 2021-04-11 11:37 UTC
This appears to be the originator of a number of manga that other sites scrap from.
Thanks

**Comment by TheNetsky** [comment] 2021-04-11 12:14
This is a Madara source.
It's already in the list here https://github.com/Paperback-iOS/extensions-madara/issues/24
Not sure when these will be added.

**Comment by AdrienSeon** [comment] 2021-04-11 14:50
Duplicate of https://github.com/Paperback-iOS/extensions-madara/issues/24

**Closed by AdrienSeon** 2021-04-11 14:50 UTC
